/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package remapper.bug;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import org.objectweb.asm.AnnotationVisitor;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.FieldVisitor;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.commons.ClassRemapper;
import org.objectweb.asm.commons.Remapper;

class RemapperTest {
  @Test
  void remapper() throws IOException {
    assertEquals("ok", "ok");

    byte[] bytecode = Files.readAllBytes(Paths.get("../SqlFunctions.class"));
    Remapper remapper = new Remapper() {
    };

    ClassReader classReader = new ClassReader(bytecode);
    ClassWriter classWriter = new ClassWriter(ClassWriter.COMPUTE_MAXS);

    ClassRemapper classRemapper = new ClassRemapper(classWriter, remapper);

    classReader.accept(classRemapper, ClassReader.EXPAND_FRAMES);

    byte[] outputBytecode = classWriter.toByteArray();
    
    ClassReader classReader2 = new ClassReader(outputBytecode);
    ClassWriter classWriter2 = new ClassWriter(ClassWriter.COMPUTE_MAXS);
    ClassVisitor visitor = new ClassVisitor(Opcodes.ASM9, classWriter2) {};
    classReader2.accept(visitor, ClassReader.EXPAND_FRAMES);

  }
}
